[Sys]
Mode = "dev"
Version = "2.0.1"

[DB]
Driver = "mysql"
# DSN (Data Source Name)
# https://github.com/go-sql-driver/mysql#dsn-data-source-name
DataSourceName = "demo:demo@tcp(127.0.0.1)/demo"

[Web]
Domain = "gin-example.local"
BindAddr = "0.0.0.0"
HTTPPort = "8080"

